services:
  nuxt-retailer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - NODE_ENV=development
    command: pnpm dev

  # Add more services here if needed (e.g., database, cache, etc.)
